import { StyleSheet } from 'react-native';

export const createLoginStyles = (colors) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    keyboardAvoid: {
      flex: 1,
    },
    scrollContainer: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingVertical: 30,
      paddingHorizontal: 20,
    },
    content: {},
    title: {
      fontSize: 24,
      fontWeight: '700',
      marginBottom: 6,
      color: colors.textPrimary,
      textAlign: 'center',
    },
    subtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 30,
      textAlign: 'center',
    },
    label: {
      fontWeight: '600',
      marginBottom: 5,
      color: colors.textPrimary,
      fontSize: 14,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 14,
      marginBottom: 16,
      fontSize: 14,
      color: colors.textPrimary,
      width: '100%',
      backgroundColor: colors.inputBackground,
    },
    inputError: {
      borderColor: colors.error,
      backgroundColor: colors.errorBackground,
    },
    errorContainer: {
      backgroundColor: colors.errorBackground,
      borderWidth: 1,
      borderColor: colors.error,
      borderRadius: 8,
      padding: 12,
      marginBottom: 20,
    },
    errorText: {
      color: colors.error,
      fontSize: 12,
      marginBottom: 10,
      marginTop: -10,
    },
    submitBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 5,
      marginBottom: 15,
    },
    submitBtnDisabled: {
      backgroundColor: colors.primaryLight,
    },
    submitText: {
      color: colors.buttonText,
      fontWeight: '600',
      fontSize: 16,
    },
    forgotPasswordBtn: {
      marginBottom: 20,
      alignItems: 'center',
    },
    forgotPasswordText: {
      color: colors.primary,
      fontWeight: '600',
      textDecorationLine: 'underline',
      fontSize: 14,
    },
    dividerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 18,
    },
    divider: {
      flex: 1,
      height: 1,
      backgroundColor: colors.border,
    },
    dividerText: {
      marginHorizontal: 10,
      color: colors.textSecondary,
      fontSize: 14,
    },
    googleBtn: {
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    googleText: {
      color: colors.textPrimary,
      fontWeight: '600',
      fontSize: 14,
    },
    registerContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: 25,
    },
    registerText: {
      color: colors.primary,
      fontWeight: '600',
      fontSize: 14,
    },
    backButton: {
      backgroundColor: colors.card,
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 3,
    },
    backIcon: {
      fontSize: 22,
      color: colors.textPrimary,
    },
    successMessageContainer: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -150 }, { translateY: -50 }],
      backgroundColor: colors.success,
      padding: 15,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 300,
      zIndex: 1000,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    successMessageText: {
      color: colors.buttonText,
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
  });