import { StyleSheet } from 'react-native';

export const createRegisterStyles = (colors) => 
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    keyboardAvoid: {
      flex: 1,
    },
    container: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingVertical: 30,
      paddingHorizontal: 20,
    },
    title: {
      fontSize: 24,
      fontWeight: '700',
      marginBottom: 6,
      color: colors.textPrimary,
      textAlign: 'center',
    },
    subtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 30,
      textAlign: 'center',
    },
    label: {
      fontWeight: '600',
      marginBottom: 5,
      color: colors.textPrimary,
      fontSize: 14,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 14,
      marginBottom: 16,
      fontSize: 14,
      color: colors.textPrimary,
      width: '100%',
      backgroundColor: colors.inputBackground,
    },
    inputError: {
      borderColor: colors.error,
      backgroundColor: colors.errorBackground,
    },
    errorContainer: {
      backgroundColor: colors.errorBackground,
      borderWidth: 1,
      borderColor: colors.error,
      borderRadius: 8,
      padding: 12,
      marginBottom: 20,
    },
    errorText: {
      color: colors.error,
      fontSize: 12,
      marginBottom: 10,
      marginTop: -10,
    },
    phoneContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    pickerWrapper: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      marginRight: 10,
      backgroundColor: colors.inputBackground,
    },
    picker: {
      height: 40,
      width: 100,
      color: colors.textPrimary,
    },
    inputNoMargin: {
      marginBottom: 0,
    },
    phoneInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 14,
      fontSize: 14,
      color: colors.textPrimary,
      backgroundColor: colors.inputBackground,
      flex: 1,
    },
    submitBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 10,
    },
    submitBtnDisabled: {
      backgroundColor: colors.primaryLight,
    },
    submitText: {
      color: colors.buttonText,
      fontWeight: '600',
      fontSize: 16,
    },
    dividerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 20,
    },
    divider: {
      flex: 1,
      height: 1,
      backgroundColor: colors.border,
    },
    dividerText: {
      marginHorizontal: 12,
      color: colors.textSecondary,
      fontSize: 14,
    },
    googleBtn: {
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 14,
      borderRadius: 8,
      alignItems: 'center',
    },
    googleText: {
      color: colors.textPrimary,
      fontWeight: '600',
      fontSize: 16,
    },
    loginContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: 30,
    },
    loginText: {
      color: colors.primary,
      fontWeight: '600',
      fontSize: 16,
    },
    backButton: {
      position: 'absolute',
      top: 50,
      left: 10,
      zIndex: 10,
      backgroundColor: 'transparent',
      padding: 10,
    },
    backButtonText: {
      fontSize: 34,
      color: colors.primary,
      fontWeight: 'bold',
    },
    successMessageContainer: {
      position: 'absolute',
      top: '50%', 
      left: '50%', 
      transform: [{ translateX: -150 }, { translateY: -50 }], 
      backgroundColor: colors.success, 
      padding: 15,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 300, 
      zIndex: 1000, 
      shadowColor: colors.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    successMessageText: {
      color: colors.buttonText,
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
  });